# Basic
[[plugins]]
repo ='vim-jp/vimdoc-ja'
[[plugins]]
repo = 'thinca/vim-singleton'
if = 'has("clientserver")'
hook_source = '''
  call singleton#enable()
'''
[[plugins]]
repo ='w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'
[[plugins]]
repo = 'roxma/nvim-yarp'
lazy = 1
hook_add = '''
  let g:python3_host_prog = 'python'
'''
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
lazy = 1


# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['php', 'vim']
lazy = 1
hook_add = '''
  command! LspEnable call lsp#enable()
  let g:lsp_diagnostics_float_cursor = 1

  function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    nmap <buffer> K <plug>(lsp-definition)
  endfunction
  augroup MyAugroup
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
  augroup END
'''
[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = 'vim-lsp'
lazy = 1
hook_add = '''
  let g:lsp_settings_servers_dir = expand('~/.cache/vim-lsp-settings/servers')
'''

# AutoComplete
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_source = 'asyncomplete-lsp'
lazy = 1

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_source = 'vim-lsp'
lazy = 1

# Snippet
[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_add = '''
  let g:neosnippet#enable_conceal_markers=0
  imap <expr><Tab> neosnippet#expandable_or_jumpable() ? "<Plug>(neosnippet_expand_or_jump)" : "<Tab>"
'''
lazy = 1
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet'
lazy = 1

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
depends = 'vim-lsp'
lazy = 1

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
depends = ['vim-lsp-snippets', 'neosnippet']
on_source = 'vim-lsp'
lazy = 1

# Util
[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
  let g:neomru#file_mru_ignore_pattern .= '\|\%(^\%(.\{-}\)://\)'
  let g:neomru#file_mru_ignore_pattern .= '\|\%(^\%(//\)\)'
  let g:neomru#directory_mru_ignore_pattern .= '\|\%(^\%(.\{-}\)://\)'
  let g:neomru#directory_mru_ignore_pattern .= '\|\%(^\%(//\)\)'
'''
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
on_cmd = 'Denite'
lazy = 1
hook_add = '''
  nnoremap <Leader>u :<C-u>Denite buffer<CR>
  nnoremap <Leader>U :<C-u>Denite file_mru<CR>
  nnoremap <Leader>p :<C-u>DeniteProjectDir file/rec<CR>
  nnoremap <Leader>P :<C-u>execute 'DeniteProjectDir' '-input='.expand('<cword>') 'file/rec'<CR>
'''
hook_post_source = '''
  call denite#custom#option('_', {
      \ 'highlight_matched_char': 'Underlined',
      \ 'highlight_matched_range': 'Underlined',
      \ })

  augroup MyAugroup
    autocmd FileType denite call s:denite_settings()
  augroup END

  function! s:denite_settings() abort
    nnoremap <silent><buffer><nowait><expr> <CR> denite#do_map('do_action')
    nnoremap <silent><buffer><nowait><expr> <Tab> denite#do_map('choose_action')
    nnoremap <silent><buffer><nowait><expr> t denite#do_map('do_action', 'tabopen')
    nnoremap <silent><buffer><nowait><expr> s denite#do_map('do_action', 'split')
    nnoremap <silent><buffer><nowait><expr> v denite#do_map('do_action', 'vsplit')

    nnoremap <silent><buffer><nowait><expr> i denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><nowait><expr> * denite#do_map('toggle_select')
    nnoremap <silent><buffer><nowait><expr> d denite#do_map('do_action', 'delete')

    nnoremap <silent><buffer><nowait><expr> q denite#do_map('quit')
    nnoremap <silent><buffer><nowait><expr> j line('.') ==# line('$') ? 'gg' : 'j'
    nnoremap <silent><buffer><nowait><expr> k line('.') ==# 1 ? 'G' : 'k'
  endfunction
'''
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
on_source = ['denite.nvim']
on_cmd = 'Defx'
hook_add = '''
  nnoremap <Leader><Leader> :<C-u>Defx -buffer-name=tree<CR>
  " nnoremap <Tab> :<C-u>Defx -buffer-name=tree<CR>
'''
hook_post_source = '''
  call defx#custom#option('_', {
      \ 'root_marker': ':',
      \ 'show_ignored_files': 1,
      \ 'auto_cd': 1,
      \ })
  call defx#custom#option('tree', {
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'winwidth': 40,
      \ 'toggle': 1,
      \ 'columns': 'mark:indent:icon:filename',
      \ })
  call defx#custom#option('temp', {
      \ 'split': 'horizontal',
      \ 'toggle': 1,
      \ 'columns': 'mark:indent:icon:filename',
      \ })
  call defx#custom#column('filename', {
      \ 'min_width': 38,
      \ 'max_width': 38,
      \ })

  augroup MyAugroup
    autocmd FileType defx call s:defx_settings()

    " autocmd VimEnter * silent! autocmd! FileExplorer *
    " autocmd BufEnter * if isdirectory(expand('%:p')) || expand('%:t') ==# '~' | execute 'Defx' |  endif
  augroup END

  let g:defx_shortcuts = get(g:, 'defx_shortcuts', {})
  function! s:defx_settings() abort
    for key in keys(g:defx_shortcuts)
        execute 'nnoremap <silent><buffer><nowait><expr> _' . key . ' defx#do_action("cd", ["'.g:defx_shortcuts[key].'"])'
    endfor

    nnoremap <silent><buffer><nowait><expr> <CR> defx#is_directory() ? defx#do_action('open_or_close_tree') : defx#do_action('multi', ['drop', 'quit'])
    nnoremap <silent><buffer><nowait><expr> l defx#is_directory() ? defx#do_action('open') : defx#do_action('multi', ['drop', 'quit'])
    nnoremap <silent><buffer><nowait><expr> t defx#do_action('multi', [['open', 'tab split'], 'quit'])
    nnoremap <silent><buffer><nowait><expr> s defx#do_action('multi', [['open', 'split'], 'quit'])
    nnoremap <silent><buffer><nowait><expr> v defx#do_action('multi', [['open', 'rightbelow vsplit'], 'quit'])
    nnoremap <silent><buffer><nowait><expr> T defx#do_action('multi', ['open', 'tab split'])

    nnoremap <silent><buffer><nowait><expr> ! defx#do_action('execute_command')
    nnoremap <silent><buffer><nowait><expr> x defx#do_action('multi', ['execute_system', 'quit'])
    nnoremap <silent><buffer><nowait><expr> X defx#do_action('execute_system')
    nnoremap <silent><buffer><nowait><expr> yy defx#do_action('yank_path')
    nnoremap <silent><buffer><nowait><expr> <C-l> defx#do_action('redraw')

    nnoremap <silent><buffer><nowait><expr> h defx#do_action('cd', ['..'])
    nnoremap <silent><buffer><nowait><expr> \ defx#do_action('cd', ['/'])
    nnoremap <silent><buffer><nowait><expr> ~ defx#do_action('cd')

    nnoremap <silent><buffer><nowait><expr> * defx#do_action('toggle_select')
    xnoremap <silent><buffer><nowait><expr> * defx#do_action('toggle_select_visual')
    nnoremap <silent><buffer><nowait><expr> c defx#do_action('copy')
    nnoremap <silent><buffer><nowait><expr> m defx#do_action('move')
    nnoremap <silent><buffer><nowait><expr> d defx#do_action('remove')
    nnoremap <silent><buffer><nowait><expr> p defx#do_action('paste')
    nnoremap <silent><buffer><nowait><expr> r defx#do_action('rename')
    nnoremap <silent><buffer><nowait><expr> K defx#do_action('new_directory')
    nnoremap <silent><buffer><nowait><expr> N defx#do_action('new_file')
    nnoremap <silent><buffer><nowait><expr> % defx#do_action('new_multiple_files')

    nnoremap <silent><buffer><nowait><expr> . defx#do_action('toggle_ignored_files')
    nnoremap <silent><buffer><nowait><expr> q defx#do_action('quit')
    nnoremap <silent><buffer><nowait><expr> j line('.') ==# line('$') ? 'gg' : 'j'
    nnoremap <silent><buffer><nowait><expr> k line('.') ==# 1 ? 'G' : 'k'
    nnoremap <silent><buffer><nowait> <C-w>s :<C-u>Defx -buffer-name=temp<CR>
    nnoremap <silent><buffer><nowait> <C-w><C-s> :<C-u>Defx -buffer-name=temp<CR>
  endfunction
'''
[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'

# Quickfix
[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

# Edit
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_add = '''
  imap <C-h> <BS>
  cmap <C-h> <BS>
'''
[[plugins]]
repo = 'machakann/vim-sandwich'
on_map = '<Plug>'
hook_add = '''
  nmap ys <Plug>(sandwich-add)
  onoremap <SID>line :normal! ^vg_<CR>
  nmap <silent> yss <Plug>(sandwich-add)<SID>line
  onoremap <SID>gul g_
  nmap <silent> yS <Plug>(sandwich-add)<SID>gul

  nmap ds <Plug>(sandwich-delete)
  nmap dss <Plug>(sandwich-delete-auto)
  nmap cs <Plug>(sandwich-replace)
  nmap css <Plug>(sandwich-replace-auto)

  xmap S <Plug>(sandwich-add)
'''
hook_post_source = '''
  runtime macros/sandwich/keymap/surround.vim
'''
[[plugins]]
repo = 'kana/vim-repeat'
on_source = ['caw.vim']
hook_post_source = '''
if hasmapto('<Plug>(operator-sandwich-dot)')
  nmap . <Plug>(operator-sandwich-predot)<Plug>(repeat-.)
endif
'''
[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
'''
[[plugins]]
repo = 'kana/vim-operator-user'
lazy = 1
[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
  map _ <Plug>(operator-replace)
  map <expr> g_ ':let @*=substitute(@*, "\n", "", "g")<CR>'.'<Plug>(operator-replace)'
'''
[[plugins]]
repo ='junegunn/vim-easy-align'
on_map = [
  ['v', '<Plug>(EasyAlign)'],
]
hook_add = '''
  vmap <Enter> <Plug>(EasyAlign)
'''
# [plugins]
# repo = 'matchit.zip'
# lazy = 1
# [[plugins]]
# repo = 'vimtaku/hl_matchit.vim'
# depends = 'matchit.zip'
[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>'
hook_add = '''
  nmap gc <Plug>(caw:prefix)
  xmap gc <Plug>(caw:prefix)
'''
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php']
[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>'
hook_add = '''
map *   <Plug>(asterisk-*)
map #   <Plug>(asterisk-#)
map g*  <Plug>(asterisk-g*)
map g#  <Plug>(asterisk-g#)
map z*  <Plug>(asterisk-z*)
map gz* <Plug>(asterisk-gz*)
map z#  <Plug>(asterisk-z#)
map gz# <Plug>(asterisk-gz#)
'''

# FileType
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-'
hook_add = '''
  let g:netrw_nogx = 1
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

# VCS
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_post_source = '''
  let g:gina#process#command = "git --no-pager -c core.editor= -c color.status=always"

  call gina#custom#command#option('status', '-b|--branch')
  call gina#custom#command#option('status', '-s|--short')
  call gina#custom#command#option('commit', '-v|--verbose')
  call gina#custom#command#option('log', '--graph')
  call gina#custom#action#alias('branch', 'merge:no-ff', 'commit:merge:no-ff')

  call gina#custom#mapping#nmap(
      \ 'branch', 'D',
      \ ':<C-u>call gina#action#call("branch:delete")<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'branch', 'N',
      \ ':<C-u>call gina#action#call("branch:new")<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'branch', 'R',
      \ ':<C-u>call gina#action#call("branch:move")<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'status', 'dp',
      \ ':<C-u>call gina#action#call("diff:preview")<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'status', '<C-^>',
      \ ':<C-u>Gina commit<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'commit', '<C-^>',
      \ ':<C-u>Gina status<CR>',
      \ {'noremap': 1, 'silent': 1},
      \)
  call gina#custom#mapping#nmap(
      \ 'log', '<C-l>',
      \ ':<C-u>Gina log<CR><C-l>',
      \ {'noremap': 1, 'silent': 1},
      \)
'''
hook_add = '''
  nnoremap <Leader>gs :<C-u>Gina status --opener=tabedit<CR>
  nnoremap <Leader>gc :<C-u>Gina commit --opener=vsplit<CR>
  nnoremap <Leader>gC :<C-u>Gina commit --amend --opener=vsplit<CR>
  nnoremap <Leader>gb :<C-u>Gina branch --all --opener=split<CR>
  nnoremap <Leader>gl :<C-u>Gina log --opener=vsplit<CR>
  nnoremap <Leader>gL :execute 'Gina log --opener=vsplit -- '.expand('%:p')<CR>
  nnoremap <Leader>gn :<C-u>Gina log --name-status --opener=vsplit<CR>
  nnoremap <Leader>gN :execute 'Gina log --name-status --opener=vsplit -- '.getcwd()<CR>
'''
