scriptencoding utf-8

colorscheme hybrid

" ツールバー、メニュー無効
set guioptions-=e guioptions-=m guioptions-=T
" スクロールバー無効
set guioptions-=r guioptions-=R guioptions-=l guioptions-=L
" コンソールダイアログを使う
set guioptions+=c

if IsWindows()
  set guifont=Ricty_Diminished:h14:cSHIFTJIS

  " インサートモードを抜けるときにIMEをオフに
  inoremap <silent> <ESC> <ESC><ESC>:set iminsert=0<CR>
  autocmd GUIEnter * set transparency=240

endif
if IsMac()
  set guifont=Ricty\ Regular:h14

  set macmeta
  set transparency=10
endif
