scriptencoding utf-8

colorscheme hybrid

"window位置固定
let g:save_window_file = expand('~/vimfiles/.vimwinpos')
augroup SaveWindow
  autocmd!
  autocmd VimLeavePre * call s:save_window()
  function! s:save_window()
    let options = [
      \ 'set columns=' . &columns,
      \ 'set lines=' . &lines,
      \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
      \ ]
    call writefile(options, g:save_window_file)
  endfunction
augroup END

if filereadable(g:save_window_file)
  execute 'source' g:save_window_file
endif


"#gui設定
"ツールバー、メニュー無効
set guioptions-=e guioptions-=m guioptions-=T
"スクロールバー無効
set guioptions-=r guioptions-=R guioptions-=l guioptions-=L
"コンソールダイアログを使う
set guioptions+=c

if IsWindows()
  set guifont=Ricty_Diminished:h14:cSHIFTJIS
elseif(IsMac())
  set guifont=Ricty\ Regular:h14
endif
